apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-ssh-init-script
  namespace: sample
data:
  setup.sh: |
    #!/bin/bash
    set -e

    echo "[INFO] Installing packages..."
    apt update && DEBIAN_FRONTEND=noninteractive apt install -y sudo openssh-server vim bash

    echo "[INFO] Creating user..."
    useradd -m -s /bin/bash {{ .Values.ssh.user }}
    echo "{{ .Values.ssh.user }} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    echo "[INFO] Setting up SSH..."
    mkdir -p /home/{{ .Values.ssh.user }}/.ssh
    cp /mnt/keys/id_rsa.pub /home/{{ .Values.ssh.user }}/.ssh/authorized_keys
    chmod 700 /home/{{ .Values.ssh.user }}/.ssh
    chmod 600 /home/{{ .Values.ssh.user }}/.ssh/authorized_keys
    chown -R 1001:1001 /home/{{ .Values.ssh.user }}/.ssh

    mkdir -p /var/run/sshd

