apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-script
data:
  setup.sh: |
    #!/bin/sh
    set -eux

    echo "[INFO] Installing packages..."
    apt update && DEBIAN_FRONTEND=noninteractive apt install -y sudo openssh-server vim bash

    echo "[INFO] Creating user..."
    useradd -m -s /bin/bash ubuntu || true
    echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    echo "[INFO] Setting up SSH..."
    mkdir -p /home/ubuntu/.ssh
    cp /mnt/keys/id_rsa.pub /home/ubuntu/.ssh/authorized_keys
    chmod 700 /home/ubuntu/.ssh
    chmod 600 /home/ubuntu/.ssh/authorized_keys
    chown -R 1001:1001 /home/ubuntu/.ssh

    echo "[INFO] Preparing SSHD..."
    mkdir -p /var/run/sshd
    chown root:root /var/run/sshd
    chmod 0755 /var/run/sshd

    echo "[INFO] Creating sshd user if not exists..."
    id sshd 2>/dev/null || useradd -r -s /usr/sbin/nologin -d /var/run/sshd sshd

    echo "[INFO] Copying sshd binary for postStart..."
    cp /usr/sbin/sshd /mnt/ssh-bin/sshd

    echo "[INFO] Copying required shared libraries dynamically..."
    mkdir -p /mnt/ssh-lib

    ldd /usr/sbin/sshd | awk '{print $3}' | while read lib; do
    if [ -n "$lib" ] && [ -e "$lib" ]; then
    echo "[INFO] Copying $lib"
    cp "$lib" /mnt/ssh-lib/
    fi
    done

    cp /etc/passwd /mnt/passwd/passwd
    cp /etc/group /mnt/passwd/group
    cp /etc/shadow /mnt/passwd/shadow


