apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-ssh-init-script
  namespace: sample
data:
  setup.sh: |
    #!/bin/bash
    set -euo pipefail

    log() { echo "[INFO] $1"; }
    fail() { echo "[ERROR] $1" >&2; exit 1; }

    log "Installing packages..."
    apt update && DEBIAN_FRONTEND=noninteractive apt install -y sudo openssh-server vim bash || fail "Package installation failed"

    log "Creating user..."
    id {{ .Values.ssh.user }} >/dev/null 2>&1 || useradd -m -s /bin/bash {{ .Values.ssh.user }} || fail "User creation failed"
    echo "{{ .Values.ssh.user }} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers || fail "Failed to modify sudoers"

    log "Setting up SSH..."

    mkdir -p /home/{{ .Values.ssh.user }}/.ssh || fail "Failed to create .ssh directory"
    if [[ ! -f /mnt/keys/id_rsa.pub ]]; then
    fail "Public key not found at /mnt/keys/id_rsa.pub"
    fi
    cp /mnt/keys/id_rsa.pub /home/{{ .Values.ssh.user }}/.ssh/authorized_keys || fail "Failed to copy public key"
    chmod 700 /home/{{ .Values.ssh.user }}/.ssh || fail "chmod 700 failed"
    chmod 600 /home/{{ .Values.ssh.user }}/.ssh/authorized_keys || fail "chmod 600 failed"
    chown -R 1001:1001 /home/{{ .Values.ssh.user }}/.ssh || fail "chown failed"

    mkdir -p /var/run/sshd || fail "Failed to create /var/run/sshd"

