apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-setup-script
data:
  setup.sh: |
    #!/bin/sh
    set -e

    echo "[INFO] Installing packages..."
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      sudo openssh-server vim bash procps net-tools

    echo "[INFO] Creating user..."
    useradd -m -s /bin/bash ubuntu
    echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    echo "[INFO] Configuring SSH..."
    mkdir -p /var/run/sshd
    mkdir -p /home/ubuntu/.ssh
    chmod 700 /home/ubuntu/.ssh
    echo "${PUBLIC_KEY}" > /home/ubuntu/.ssh/authorized_keys
    chmod 600 /home/ubuntu/.ssh/authorized_keys
    chown -R ubuntu:ubuntu /home/ubuntu/.ssh

    sed -i 's/#Port 22/Port ${SSH_PORT}/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
