apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-ssh-setup
  namespace: sample
data:
  setup.sh: |
    #!/bin/bash
    set -e

    echo "[INFO] Installing packages..."
    apt update
    DEBIAN_FRONTEND=noninteractive apt install -y sudo openssh-server vim bash procps net-tools

    echo "[INFO] Creating user..."
    useradd -m -s /bin/bash {{ .Values.ssh.user }}
    echo "{{ .Values.ssh.user }} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

    echo "[INFO] Setting up SSH directory..."
    mkdir -p /home/{{ .Values.ssh.user }}/.ssh
    cp /mnt/keys/id_rsa.pub /home/{{ .Values.ssh.user }}/.ssh/authorized_keys
    chown -R {{ .Values.ssh.user }}:{{ .Values.ssh.user }} /home/{{ .Values.ssh.user }}/.ssh
    chmod 700 /home/{{ .Values.ssh.user }}/.ssh
    chmod 600 /home/{{ .Values.ssh.user }}/.ssh/authorized_keys

    echo "[INFO] SSH config..."
    mkdir -p /var/run/sshd
    sed -i 's/#Port 22/Port {{ .Values.ssh.port }}/' /etc/ssh/sshd_config
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' /etc/ssh/sshd_config
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

    echo "[INFO] Starting sshd..."
    /usr/sbin/sshd -D
