apiVersion: batch/v1
kind: Job
metadata:
  name: generate-ssh-key
spec:
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: ssh-key-vol
          emptyDir: {}
      containers:
        - name: keygen
          image: ubuntu:22.04
          command: ["/bin/bash", "-c"]
          args:
            - |
              apt update && apt install -y openssh-client;
              ssh-keygen -t rsa -b 2048 -f /mnt/ssh-key/id_rsa -N '';
              kubectl create secret generic ssh-key-secret \
                --from-file=id_rsa=/mnt/ssh-key/id_rsa \
                --from-file=id_rsa.pub=/mnt/ssh-key/id_rsa.pub \
                --dry-run=client -o yaml | kubectl apply -f -
          volumeMounts:
            - name: ssh-key-vol
              mountPath: /mnt/ssh-key
