apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh
  namespace: sample
spec:
  selector:
    app: ubuntu-ssh
  type: NodePort
  ports:
    - name: ssh
      port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}
      nodePort: 30222