apiVersion: v1
kind: Service
metadata:
  name: { { .Values.serviceName } }
spec:
  type: NodePort
  selector:
    app: { { .Release.Name } }
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
      nodePort: { { .Values.ssh.exposePort } }
