apiVersion: v1
kind: Service
metadata:
  name: ubuntu-ssh
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: {{ .Values.ssh.port }}
      nodePort: 30222
  selector:
    app: ubuntu-ssh
