apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  type: NodePort
  ports:
    - name: ssh
      port: {{ .Values.ssh.port }}
      targetPort: {{ .Values.ssh.port }}
      nodePort: 30222